services:
  postgres:
    image: postgres:11-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: webapp_dev
      POSTRES_HOST_AUTH_METHOD: trust

  web:
    build: .
    depends_on:
      - postgres
    ports:
      - 5000:5000
      - 9229:9229 # <- e nables debugging
    volumes:
      - .:/usr/local/sbin
      - /usr/local/sbin/node_modules
    command: yarn run dev
    environment:
      DATABASE_URL: postgres://postgres@postgres/webapp_dev
      PORT: 5000
